### ISSUE TITLE
微调结果文件

### ISSUE THREAD

**Issue by WileMore** [xing61/zzz-api#21]
微调模型后产生的结果文件支持下载吗？

**Comment by xing61** [comment]
问题解决了。支持下载了

**Comment by WileMore** [comment]
> 问题解决了。支持下载了

job_stat = client.fine_tuning.jobs.retrieve("finetune.id")
files_list = client.files.list()
print(files_list)

fine_tune_result_file = client.fine_tuning.jobs.retrieve(job_stat.id).result_files
print(fine_tune_result_file)
result_file = client.files.retrieve(fine_tune_result_file[0])
print(result_file.id)
result_content = client.files.content(result_file.id)
print(result_content)

print(result_content)输出的结果是：<openai._legacy_response.HttpxBinaryResponseContent object at 0x0000018B4289BDA0>

**Comment by WileMore** [comment]
搞定了，非常感谢，还是需要用base64做一次内容的decode到utf-8才能得到正确的格式，
