### ISSUE TITLE
client.fine_tuning.jobs.list() is error

### ISSUE THREAD

**Issue by skandbug** [xing61/zzz-api#22]
```
from openai import OpenAI
client = OpenAI(api_key=api_key, base_url=base_url)

client.fine_tuning.jobs.list()
```

This code cannot be debugged to get results when using the Token you provided.
Is it because your API doesn't work when repackaging?

**Comment by skandbug** [comment]
![image](https://github.com/xing61/zzz-api/assets/52226009/2b609140-1a21-4c42-807f-caab184021ce)

**Comment by xing61** [comment]
已修复
