### ISSUE TITLE
说 API 错的 怎么搞

### ISSUE THREAD

**Issue by thunderwin** [xing61/zzz-api#23]
******
Could not load OpenAI embedding model. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

Consider using embed_model='local'.
Visit our documentation for more embedding options: https://docs.llamaindex.ai/en/stable/module_guides/models/embeddings.html#modules
******

**Comment by xing61** [comment]
意思似乎是说你没有设置环境变量
