### ISSUE TITLE
batch里的jsonl文件的content只支持英文吗

### ISSUE THREAD

**Issue by liyuduo** [xing61/zzz-api#25]

**Comment by xing61** [comment]
没有吧，现在提示什么呢？

**Comment by liyuduo** [comment]
resp = client.files.create(）执行这个的时候一直报错UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-14: ordinal not in range(128)，我的jsonl文件内容请求是这样的{"custom_id":"request-1", " method": "POST", "url": "/v1/chat/completions", "body": {"model": "gpt-4o", "messages": [{"role": "system", "content": "You are a helpful assistant."},{"role": "user", "content": "请判断以下句子是由人工撰写还是由AI生成的，如果是由人工生成的只回答0，否则只回答1：’𝐜𝐡𝐢𝐜 𝐦𝐞𝐦𝐨𝐫𝐲少女刚需。((抓个眼熟的宝穿~  外扩胸垫系列.去年买过的请举手~平地起高楼bbb入~这款增加更多少女设计 基础纯欲*  更适合甜妹体质的工装裤.* 没有人不需要！已列为我衣柜中便携出门常穿单品𝐭𝐨𝐩𝟏. http://t.cn/A6NgvGxh ​‘。"}],"max_tokens": 1000}}

**Comment by xing61** [comment]
这是上传文件吧，是utf8编码么，这意思看起来是编码问题，和batch关系不大

**Comment by liyuduo** [comment]
> 没有吧，现在提示什么呢？

resp = client.files.create(）执行这个的时候一直报错UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-14: ordinal not in range(128)，我的jsonl文件内容请求是这样的
{"custom_id":"request-1", " method": "POST", "url": "/v1/chat/completions", "body": {"model": "gpt-4o", "messages": [{"role": "system", "content": "You are a helpful assistant."},{"role": "user", "content": "请判断以下句子是由人工撰写还是由AI生成的，如果是由人工生成的只回答0，否则只回答1：’𝐜𝐡𝐢𝐜 𝐦𝐞𝐦𝐨𝐫𝐲少女刚需。((抓个眼熟的宝穿~ 外扩胸垫系列.去年买过的请举手平地起高楼bbb入这款增加更多少女设计 基础纯欲* 更适合甜妹体质的工装裤.* 没有人不需要！已列为我衣柜中便携出门常穿单品𝐭𝐨𝐩𝟏. http://t.cn/A6NgvGxh ​‘。"}],"max_tokens": 1000}}

> 这是上传文件吧，是utf8编码么，这意思看起来是编码问题，和batch关系不大
写文件时utf8，读的时候也用utf8，但是就是老报错，大佬有没有解决办法啊

**Comment by xing61** [comment]
文件编码问题，用工具检查下，改编码成gpt支持的编码

**Comment by liyuduo** [comment]
> 文件编码问题，用工具检查下，改编码成gpt支持的编码

好的好的  我再看一下  谢谢

**Comment by liyuduo** [comment]
![image](https://github.com/user-attachments/assets/47ca4501-5771-452c-9674-f4141dac0fb4)
这个请求数是我文件的请求数还是到现在执行的条数？
